// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfEaGO7Z01CTP6pjjz7WQokVX0DbNAHbc',
    appId: '1:741117586397:web:5e730c78f9ef7bdf496434',
    messagingSenderId: '741117586397',
    projectId: 'gestor-inventario-4aaa6',
    authDomain: 'gestor-inventario-4aaa6.firebaseapp.com',
    storageBucket: 'gestor-inventario-4aaa6.firebasestorage.app',
    measurementId: 'G-PXDPL6TJSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzAQAou4lW2CQX1nDJifWUv3c1lAlON4',
    appId: '1:741117586397:android:5778a65761418874496434',
    messagingSenderId: '741117586397',
    projectId: 'gestor-inventario-4aaa6',
    storageBucket: 'gestor-inventario-4aaa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegkgQM0dP7Xz_YEAURkkWEi7O3GBJTJo',
    appId: '1:741117586397:ios:8c24df546709b7f9496434',
    messagingSenderId: '741117586397',
    projectId: 'gestor-inventario-4aaa6',
    storageBucket: 'gestor-inventario-4aaa6.firebasestorage.app',
    iosBundleId: 'com.example.gestorInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegkgQM0dP7Xz_YEAURkkWEi7O3GBJTJo',
    appId: '1:741117586397:ios:8c24df546709b7f9496434',
    messagingSenderId: '741117586397',
    projectId: 'gestor-inventario-4aaa6',
    storageBucket: 'gestor-inventario-4aaa6.firebasestorage.app',
    iosBundleId: 'com.example.gestorInventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfEaGO7Z01CTP6pjjz7WQokVX0DbNAHbc',
    appId: '1:741117586397:web:314395429689c19c496434',
    messagingSenderId: '741117586397',
    projectId: 'gestor-inventario-4aaa6',
    authDomain: 'gestor-inventario-4aaa6.firebaseapp.com',
    storageBucket: 'gestor-inventario-4aaa6.firebasestorage.app',
    measurementId: 'G-XPZ89SL9SD',
  );

}